import { Button, VerticalBox , TabWidget,  CheckBox, GroupBox, HorizontalBox, TextEdit} from "std-widgets.slint";

import { AvaSetting, AvaSettings } from "global.slint";

import { AboutPage } from "about.slint";

import { BatterySavePage, BatteryCallbacks } from "batterysave.slint";

export {
    AvaSetting,
    AvaSettings
}

export { BatteryCallbacks }

export AppWindow := Window {
    title: "Green Dam Battery Contorl";
    min-width: 500px;
    height: 1000px;
    TabWidget {
        Tab {
            title: "Battery Set";
            BatterySavePage { 
            }
        }
        Tab {
            title: "About";
            AboutPage {
            }
        }
    }
}
